"""create checkpointer tables

Revision ID: 41c1e13fc246
Revises: 
Create Date: 2026-07-08 22:02:31.417461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41c1e13fc246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('blob', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version')
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('v')
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('blob', postgresql.BYTEA(), nullable=True),
    sa.Column('task_path', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_table('checkpoint_blobs')
    # ### end Alembic commands ###
